### ISSUE TITLE
Last will problem

### ISSUE THREAD

**Issue by radimsejk** [plapointe6/EspMQTTClient#106]
## Description of the problem
I have a lot of ESP8266 nodes. I want to have separate topic of lastwill on each node that looks like this:
`bomba/myUID/lastwill` where myUID = esp8266 MAC so I did this in Setup():
```
String myUID = WiFi.macAddress();   //which is 24:A1:60:3A:BF:35
myUID.replace(":", "");             //which is 24A1603ABF35
client.enableLastWillMessage(("bomba/" + myUID + "/lastwill").c_str(), "OFFLINE", false); 
```
and when I disconnect the module I see no message on MQTT.

But it works when I do this:
```
client.enableLastWillMessage("bomba/24A1603ABF35/lastwill", "OFFLINE", false);
```

and I have even tried this with no luck:
```
String s = "bomba/" + myUID + "/lastwill";
client.enableLastWillMessage(s.c_str(), "OFFLINE", false);
```
## Versions
- ESPMQTTClient lib: 1.13.3
- PubSubClient lib: 2.8.0
- Arduino ESP32 / ESP8622 core: 3.0.0

## Hardware
- Board type : ESP8266
- Board model : Wemos D1 Mini

**Comment by BrianRossmajer** [comment]
If you've proven the library works per spec, ie. when you pass in a string... then it's not a bug when it doesn't work in a different context.   Given the warnings around using c_str() in the manual, my guess is that your last example will work fine if you define the String s in a more global scope, so that c_str stays valid -- or allocate some string space and strcpy the topic into it.

**Comment by radimsejk** [comment]
I have tried to define String s globally and assign to it right before lastwill enabling with no luck like this:
```
String ss = "";

void setup(){
...
  ss = "bomba" + myUID + "/lastwill";
  client.enableLastWillMessage(ss.c_str(), "I am going offline");  // You can activate the retain flag by setting the third parameter to true
...
}
```

And it worked. Thank you very much for pointing it out.
