### ISSUE TITLE
Possibility to set static IP address

### ISSUE THREAD

**Issue by Gugiman** [plapointe6/EspMQTTClient#28]
Hello,

by initializing `EspMQTTClient` with wifi SSID and password it would be great when I could also associate a static IP to it for monitoring cases.

Is this a huge thing to implement?

**Comment by plapointe6** [comment]
You can get to the same result by using the name of the device instead. If you take a look to [this](https://github.com/plapointe6/EspMQTTClient/blob/master/examples/SimpleMQTTClient/SimpleMQTTClient.ino) exemple, the client name will be "TestClient". Then, you can do commands like "ping TestClient" or go to "TestClient.local" in your browser if your Esp host a web server.

You can also assign DHCP reservations in your router to assign static ip adresses to your Esps.

Now, it's also possible to assign static ip adresses programmatically, but I wont work on this because of the two workaroud mentionned above. If someone propose a pull request that add the functionnality while allowing both ESP8266 and ESP32 compatibility, I will be willing to merge it.

Here some exemples of static IP handling : 
https://circuits4you.com/2018/03/09/esp8266-static-ip-address-arduino-example/
https://randomnerdtutorials.com/esp32-static-fixed-ip-address-arduino-ide/

Regards.
